version: '3.1'
# docker-compose exec -T mariadb mysql -uroot -pmysecretrootpassword < mydump.sql
services:
  db:
    image: library/mysql:8.0
    # NOTE: use of "mysql_native_password" is not recommended: https://dev.mysql.com/doc/refman/8.0/en/upgrading-from-previous-series.html#upgrade-caching-sha2-password
    # (this is just an example, not intended to be a production configuration)
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example
    volumes:
      - /home/miley/ed_homework/homework/users_20221126_021742.sql:/tmp/dump.sql
    ports:
      - 3306:3306
